### ISSUE TITLE
关于如何使用Github上已有的项目

### ISSUE THREAD

**Issue by longzhenren** [buaa21/summer2020#45]
rt
比如 我想做一个基于ADB的项目 
但是将SDK中现成的adb.exe集成到程序里不方便编译出exe文件
而且只能通过os.popen(command) 调用，python只起到了一个调用命令行的作用 可移植性不好 技术含量不高
而Github上正好有一个python adb的项目…… https://github.com/google/python-adb
请问将代码下载到本地之后应该如何直接调用其中的方法呢？按照该项目readme的操作作为库安装会报错……依赖能装的都装了
另一个项目Scrcpy也是如此

**Comment by crclz** [comment]
你把pip报错信息发出来

**Comment by longzhenren** [comment]
> 你把pip报错信息发出来
问题描述里报错的不是pip 是运行这个库的setup.py
现在adb可以安装 但是依赖装不上
pip的报错是这样的：
PS D:\Git> pip install python-libusb1
ERROR: Could not find a version that satisfies the requirement python-libusb1 (from versions: none)
ERROR: No matching distribution found for python-libusb1
PS D:\Git> pip install pyinstaller
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\hljzh\appdata\local\programs\python\python38\python.exe' 'c:\users\hljzh\appdata\local\programs\python\python38\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\hljzh\AppData\Local\Temp\pip-build-env-6erpc6ho\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (42 lines):
  Traceback (most recent call last):
    File "c:\users\hljzh\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "c:\users\hljzh\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "c:\users\hljzh\appdata\local\programs\python\python38\lib\site-packages\pip\__main__.py", line 26, in <module>
      sys.exit(_main())
    File "c:\users\hljzh\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\cli\main.py", line 73, in main
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "c:\users\hljzh\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\commands\__init__.py", line 104, in create_command
      module = importlib.import_module(module_path)
    File "c:\users\hljzh\appdata\local\programs\python\python38\lib\importlib\__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 783, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "c:\users\hljzh\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\commands\install.py", line 17, in <module>
      from pip._internal.cli.req_command import RequirementCommand, with_cleanup
    File "c:\users\hljzh\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\cli\req_command.py", line 16, in <module>
      from pip._internal.index.collector import LinkCollector
    File "c:\users\hljzh\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\index\collector.py", line 14, in <module>
      from pip._vendor import html5lib, requests
    File "c:\users\hljzh\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\requests\__init__.py", line 125, in <module>
      from . import utils
    File "c:\users\hljzh\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\requests\utils.py", line 25, in <module>
      from . import certs
    File "c:\users\hljzh\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\requests\certs.py", line 15, in <module>
      from pip._vendor.certifi import where
    File "c:\users\hljzh\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\certifi\__init__.py", line 1, in <module>
      from .core import contents, where
    File "c:\users\hljzh\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\certifi\core.py", line 12, in <module>
      from importlib.resources import path as get_path, read_text
    File "c:\users\hljzh\appdata\local\programs\python\python38\lib\importlib\resources.py", line 11, in <module>
      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401
    File "c:\users\hljzh\appdata\local\programs\python\python38\lib\site-packages\typing.py", line 1359, in <module>
      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
    File "c:\users\hljzh\appdata\local\programs\python\python38\lib\site-packages\typing.py", line 1007, in __new__
      self._abc_registry = extra._abc_registry
  AttributeError: type object 'Callable' has no attribute '_abc_registry'
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\hljzh\appdata\local\programs\python\python38\python.exe' 'c:\users\hljzh\appdata\local\programs\python\python38\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\hljzh\AppData\Local\Temp\pip-build-env-6erpc6ho\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.

**Comment by longzhenren** [comment]
> 你把pip报错信息发出来
运行时候报错是这样的：
FileNotFoundError: Could not find module 'libusb-1.0.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by crclz** [comment]
尝试用一下python3.6版本。https://github.com/google/python-adb#120 这个地方显示，支持到3.6版本。
